services:
  postgres_db:
    image: postgres:15-alpine
    container_name: smarttodo_postgres
    restart: no
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: SmartToDo
      TZ: Europe/Kiev
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql/actual_file.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - smarttodo_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: smarttodo_app
    restart: no
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - smarttodo_network

volumes:
  postgres_data:

networks:
  smarttodo_network:
    driver: bridge